# Generated by Django 6.0.2 on 2026-05-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="category",
            field=models.CharField(
                choices=[
                    ("Road Issue", "Road Issue"),
                    ("Garbage", "Garbage"),
                    ("Water Leakage", "Water Leakage"),
                    ("Electricity", "Electricity"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
    ]
